[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
#identifier = "dpcK3G40VS"
weight = 10

[[main]]
name = "Tools"
pageRef = "madTools"
#identifier = "UNxn7lkosO"
weight = 20

[[main]]
name = "Projects"
pageRef = "projects"
#identifier = "UNxn7lkosO"
weight = 30

[[main]]
name = "Talks"
pageRef = "talks"
#identifier = "GDe8QwrOjY"
weight = 40

[[main]]
name = "Blog"
pageRef = "posts"
#identifier = "AgcyRLUGjj"
weight = 50

[[main]]
name = "Contact"
pageRef = "contact"
#identifier = "iIRlqF1wAb"
weight = 60

[[footer]]
none = "none"
